Nesse notebook irei tratar toda limpeza dos dados, deixando o mais padrão possivel para que as analise possam ser feitas com regularidade.

In [1]:
# Importações das libs que vamos utilizar no notebook.
from pathlib import Path
import pandas as pd

In [ ]:
# Criação das variaveis com os caminhos respectivos de cada pasta.
BASE_DIR = Path.cwd().parents[0]
DATA_FOLDER = BASE_DIR / "data"
RAW_DIR = DATA_FOLDER / "raw"
RAW_FILE = RAW_DIR / "respostas_google_forms.csv"

In [3]:
# Importando a base de dados para darmos inicio a limpeza e tratamento de dados.
respostas_raw = pd.read_csv(RAW_FILE)
respostas = respostas_raw.copy()

respostas.head()

,Carimbo de data/hora,Nome completo:,Qual sua Faixa etária,Você tem acesso frequente à internet?,Quais dispositivos você usa no dia a dia?,Você possui algum dispositivo inteligente em casa? Marque todos que você possui.,Você acha que esses dispositivos podem trazer riscos de segurança?,Você já ouviu falar em Internet das Coisas (IoT)?,"Você já fez algum curso de tecnologia, informática ou programação?","Na sua opinião, como a tecnologia pode te ajudar mais no dia a dia?"
0,16/05/2026 19:26:42,Robertt Oliveira,18 a 24 anos,Sim,Notebook / laptop,"Caixa de som inteligente (ex: Alexa, Google Nest)",Sim,Sim,Sim,Com estudos e pesquisas
1,16/05/2026 19:27:46,Francisco Gabriel Sousa da silva,18 a 24 anos,Sim,"Celular / smartphone, Notebook / laptop",Smart TV,Sim,Não,Sim,"Ajuda em criação de site, sistemas até com pla..."
2,16/05/2026 19:35:00,Anna Gabriely de Oliveira Araujo,18 a 24 anos,Sim,"Celular / smartphone, Notebook / laptop",Smart TV,Sim,Não,Sim,me ajuda a acessar informações de maneira mais...
3,16/05/2026 19:42:13,Adrian Lucas Pinheiro Silva,18 a 24 anos,Sim,"Celular / smartphone, Computador de mesa (desk...",Smart TV,Sim,Sim,Sim,a tecnologia pode ser aplicada a basicamente t...
4,16/05/2026 19:43:09,Nathanael Rodrigues Cruz,18 a 24 anos,Sim,"Celular / smartphone, Computador de mesa (desk...","Smart TV, Relógio inteligente (smartwatch)",Sim,Não,Sim,Organizações e otimização.

Um ponto que foi identificado na analise exploratória dos dados, foi que os nomes das colunas herdaram diretamente as perguntas. Irei renomea-las para deixar mais simples e direto o processo de analise.

In [5]:
colunas_rename = {
    'Carimbo de data/hora': 'data_hora',
    'Nome completo:': 'nome',
    'Qual sua Faixa etária': 'faixa_etaria',
    'Você tem acesso frequente à internet?': 'acesso_internet',
    'Quais dispositivos você usa no dia a dia?': 'dispositivos_uso',
    'Você possui algum dispositivo inteligente em casa? Marque todos que você possui.': 'disp_inteligentes_casa',
    'Você acha que esses dispositivos podem trazer riscos de segurança?': 'risco_seguranca_disp',
    'Você já ouviu falar em Internet das Coisas (IoT)?': 'conhece_iot',
    'Você já fez algum curso de tecnologia, informática ou programação?': 'curso_tecnologia',
    'Na sua opinião, como a tecnologia pode te ajudar mais no dia a dia?': 'opiniao_tec_dia_a_dia',
}

respostas = respostas.rename(columns=colunas_rename)

respostas.head()

,data_hora,nome,faixa_etaria,acesso_internet,dispositivos_uso,disp_inteligentes_casa,risco_seguranca_disp,conhece_iot,curso_tecnologia,opiniao_tec_diaadia
0,16/05/2026 19:26:42,Robertt Oliveira,18 a 24 anos,Sim,Notebook / laptop,"Caixa de som inteligente (ex: Alexa, Google Nest)",Sim,Sim,Sim,Com estudos e pesquisas
1,16/05/2026 19:27:46,Francisco Gabriel Sousa da silva,18 a 24 anos,Sim,"Celular / smartphone, Notebook / laptop",Smart TV,Sim,Não,Sim,"Ajuda em criação de site, sistemas até com pla..."
2,16/05/2026 19:35:00,Anna Gabriely de Oliveira Araujo,18 a 24 anos,Sim,"Celular / smartphone, Notebook / laptop",Smart TV,Sim,Não,Sim,me ajuda a acessar informações de maneira mais...
3,16/05/2026 19:42:13,Adrian Lucas Pinheiro Silva,18 a 24 anos,Sim,"Celular / smartphone, Computador de mesa (desk...",Smart TV,Sim,Sim,Sim,a tecnologia pode ser aplicada a basicamente t...
4,16/05/2026 19:43:09,Nathanael Rodrigues Cruz,18 a 24 anos,Sim,"Celular / smartphone, Computador de mesa (desk...","Smart TV, Relógio inteligente (smartwatch)",Sim,Não,Sim,Organizações e otimização.

In [6]:
respostas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   data_hora               19 non-null     object
 1   nome                    19 non-null     object
 2   faixa_etaria            19 non-null     object
 3   acesso_internet         19 non-null     object
 4   dispositivos_uso        19 non-null     object
 5   disp_inteligentes_casa  19 non-null     object
 6   risco_seguranca_disp    19 non-null     object
 7   conhece_iot             19 non-null     object
 8   curso_tecnologia        19 non-null     object
 9   opiniao_tec_diaadia     19 non-null     object
dtypes: object(10)
memory usage: 1.6+ KB